#!/bin/bash

# Install Ruby and Gem if missing
sudo apt install -y ruby gem

# Ruby code generator script dependencies
gem install --user-install --conservative nokogiri -v 1.6.8.1

# Generate
ruby generator/generate.rb
